### ISSUE TITLE
How to pack dds files extracted.

### ISSUE THREAD

**Issue by JulianDC** [hhrhhr/Lua-utils-for-Witcher-3#11]
I ve extracted a dds files from the texture.cache of witcher3. How to pack it back after edition. Does this thing can do it?

**Comment by hhrhhr** [comment]
Use official modkit - https://www.nexusmods.com/witcher3/news/12550/

**Comment by JulianDC** [comment]
can you please explain how to exact do packing? 

I ve downloaded ModKit. Seems like this one works only in command line mode. But I still can not understand how to pack my dds files to one cache file.

For example I have some dds textures in C:/textures_gerald_face
and i need to take output file from C:/output
how it should look?


>Понедельник, 22 января 2018, 1:16 +06:00 от Dmitry Zaitsev <notifications@github.com>:
>
>Use official modkit -  https://www.nexusmods.com/witcher3/news/12550/
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Юлиан Дель-Кампо
mustang94free@mail.ru

**Comment by hhrhhr** [comment]
I'm sorry, but this repository is not a forum about modifications. Look for the answer in the manual or in Google.
