### ISSUE TITLE
Opening *.sav files

### ISSUE THREAD

**Issue by supermax313** [hhrhhr/Lua-utils-for-Witcher-3#3]
And is it possible to write a similar script to decompress the files \* .sav The Witcher 3? Thank you in advance for your reply.

**Comment by hhrhhr** [comment]
certainly possible. if there is one to whom it will be interesting.

2015-06-21 17:55 GMT+03:00 Maxim notifications@github.com:

**Comment by supermax313** [comment]
Yes, this is interesting. The latter format of the game, which has not yet been decompressed. It is desirable to be able not only to extract the contents of the file (supposedly within XML structure), but also the back pack.
