### ISSUE TITLE
CR2W  CR2W_type.StringAnsi

### ISSUE THREAD

**Issue by Befzz** [hhrhhr/Lua-utils-for-Witcher-3#4]
https://github.com/hhrhhr/Lua-utils-for-Witcher-3/blob/master/mod_cr2w_reader.lua#L424

строка режется в начале. если:
`local u32 = r:uint32()`
а если заменить на
`local u8 = r:uint8()`
то получим длину строки  в u8 (вместе с \x00)
и не порезанную строку.

обнаружил на
`\characters\base_entities\cat_base\cat_base.w2rig"`

**Comment by hhrhhr** [comment]
название архива содержащего этот файл не помешает.

**Comment by Befzz** [comment]
`content\content0\bundles\r4items.bundle`

**Comment by hhrhhr** [comment]
посмотрел, по крайней мере в .w2rig и .w2ent длина у типа StringAnsi задается одним байтом. поменяю, но теперь что-то вылезет где было 4 байта ;) поэтому пока не закрываю.

**Comment by hhrhhr** [comment]
раз все хорошо, то и с глаз долой ;)
