### ISSUE TITLE
lua_zlib libraries for people with disabilities

### ISSUE THREAD

**Issue by ghost** [hhrhhr/Lua-utils-for-Witcher-3#6]
hi, would it be possible to include the already compiled libraries for lua_zlib compatible with your repository, I unfortunately happened to be physically and visually challenged, and I find it very difficult to work in commandline exclusively, voice recognition software is somewhat more effective with GUI, and I would appreciate some help with a shortcut by providing the compatible libraries directly in your repository

Thanks!

**Comment by hhrhhr** [comment]
if you're about ready binary of Lua and lua-zlib, they are already there:
https://github.com/hhrhhr/Lua-utils-for-Witcher-3/releases/tag/bin — lua531_lua_zlib_x64.zip

**Comment by ghost** [comment]
thank you very much!
