### ISSUE TITLE
Sorry i missing somethink? 

### ISSUE THREAD

**Issue by kilik128** [hhrhhr/Lua-utils-for-Witcher-3#7]
for /r %%f in (*.cr2w) do C:\Lua\lua-5.3.1\lua.exe mod_cr2w_reader.lua %%f H:\exportfinal 
pause

**Comment by hhrhhr** [comment]
https://github.com/hhrhhr/Lua-utils-for-Witcher-3#inspect_cr2wlua

or, in batch:

```
for /r %%f in (*.cr2w) do lua.exe inspect_cr2w.lua "%%f" > "H:\exportfinal\%%~nf.lua"
```
