### ISSUE TITLE
inspect_w3speech.lua doesn't work with Blood and Wine

### ISSUE THREAD

**Issue by antontkv** [hhrhhr/Lua-utils-for-Witcher-3#8]
Can't extract .w3speech files of Blood and Wine expansion.

![screenshot_1](https://cloud.githubusercontent.com/assets/17809291/15735242/74f5433c-28b0-11e6-84bd-d029a5989ceb.png)

**Comment by hhrhhr** [comment]
fixed - 86100ac56cdb6bb163f6c857c157a299d1dd182d
